### ISSUE TITLE
[v2] hasSession responses are not cached when no session exists

### ISSUE THREAD

**Issue by erikfried** [schibsted/sdk-js#31]
I *think* this is a bug and not by design, but I am not 100% sure:

In the v1 version responses from 'hasSession' are (optionally) cacheable when no session exists, if error.type != 'UserException'  - https://github.com/schibsted/sdk-js/blob/1.7.11/src/spid-sdk.js#L486

In the v2 version logged out responses are never cached. https://github.com/schibsted/sdk-js/blob/master/src/spid-sdk.js#L40

Given that 92% of our pageviews are not logged in, I think that if something is worth caching it is the logged out responses.

**Comment by danielbentes** [comment]
That is a change in behaviour/functionality, but I think we did it by design as that caching more often than not generated issues. Like when you log in but the cache says you're not logged in. Which is why we decided on not keeping it in the first iteration. 

There are probably some good usecases to have the caching on, at least for some seconds, as this will result in less requests. Question is, should we bring back this option now or not?

**Comment by erikfried** [comment]
Ok, yes I suppose that was basically my point; that the caching thing is typically the most complex activity in this code. It is likely a common source of errors, like our cookie problems or stale client state.

From a perspective of reducing load on backend services, it might not even be worthwhile caching the 'positive' responses, since they are a vast minority of all requests anyway.

On the other hand, from a user perspective caching might be worthwhile to get snappier UI-updates, not having to wait for network roundtrips to get user info for presentation.

**Comment by erikfried** [comment]
Feel free to just close this issue, its not a problem from my perspective. More an observation that load on your backends will increase (massively?) when all clients switch to v2.
