### ISSUE TITLE
Stateful domain name in cookie module

### ISSUE THREAD

**Issue by kjarmicki** [schibsted/sdk-js#47]
In https://github.com/schibsted/sdk-js/blob/master/src/spid-cookie.js there is a `_domain` variable which gets set when `set()` function is called. Unfortunately, case when this function was not called yet but domain name is needed occurs:

1. Visit a site with previously set SPiD session, Varnish cookie is set
2. Click on logout
3. SDK tries to update document cookie with value `SP_ID=; expires=Mon, 14 Mar 2016 11:06:39 GMT; path=/; domain=.undefined` because `set()` function was not called, therefore unsetting varnish cookie fails

Maybe default value for `_domain` should be `document.domain`?
@linnhege

**Comment by linnhege** [comment]
Hi,
Looked a bit into it now. 
We could default to document.domain, but we should ensure that domain gets set properly anyway, because it should be set. 

I was looking a bit on the old version and it seems like an empty string was set as default, but I think document.domain makes more sense. https://github.com/schibsted/sdk-js/blob/1.7.11/dist/spid-sdk-1.7.9.js#L701

**Comment by kjarmicki** [comment]
Yes, but as far as I know old SPiD called hasSession upon initialization which subsequently set proper domain, so this wasn't as big of an issue
